baseurl = "https://example.com"
languageCode = "zh-Hans"
defaultContentLanguage = "zh-cn"
title = "Hugo Theme Dream"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""
#摘要段落数
summaryLength = 1

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "/me/background.jpg"
# backgroundImageDark = ""

author = "Dream"
description = " life in for"
avatar = "/avatar.png"
headerTitle = "Hugo Theme Dream"
motto = "llllllllll"

# footerBottomText = ""

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

# email = ""

siteStartYear = 2024

favicon = "/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
hasTwitterEmbed = true
# hasCJKLanguage = true
# enableRobotsTXT = true
showReadingTime = false
showhomesummary = true

[params.advanced]
customCSS = ["css/custom.css"]
customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
