baseurl = "invmv.github.io/Notion-Hugo-dream"
languageCode = "zh-Hans"
defaultContentLanguage = "zh-cn"
title = "Hugo Theme Dream"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

#摘要段落数
summaryLength = 1

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "/me/background.jpg"
# backgroundImageDark = ""
# email = ""
author = "Dream"
description = " life in for"
avatar = "/avatar.png"
headerTitle = "Hugo Theme Dream"
motto = "llllllllll"

# footerBottomText = ""
# options
hasTwitterEmbed = true
hasCJKLanguage = true
enableRobotsTXT = true

rss = true

stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
showReadingTime = false
showhomesummary = false


# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""
siteStartYear = 2024

favicon = "/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true



# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
