baseurl = "https://invmv.github.io/Notion-Hugo-dream/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh-cn"
title = "Hugo Theme Dream"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

#摘要段落数
summaryLength = 1

[params]
# 路径切勿以 / 为开头单 路径单独为域名没问题，但是经过域名下一个 / 之后 会出现无法访问资源

favicon = "favicon.ico"
avatar = "avatar.png"
author = "Dream"
description = " life in for"
headerTitle = "Hugo Theme Dream"
motto = "hello ！ this notion for dream "

# email = ""
# footerBottomText = ""
# options

hasTwitterEmbed = true
hasCJKLanguage = true
enableRobotsTXT = true

rss = true

stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
showReadingTime = false
showhomesummary = false

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "/me/background.jpg"
# backgroundImageDark = ""

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""
siteStartYear = 2024

# Syntax highlighting
# customSyntaxHighlighting = true

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
